server:
  port: 9000

spring:

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: noti
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    #http request logging
    org.apache.coyote.http11: debug
#    com.example.notiservice: debug
#    org:
#      hibernate:
#        SQL: debug
#        type.descriptor.sql.BasicBinder: trace
