server:
  port: 9002

spring:

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: noti
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

