spring:

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: noti
    producer:
      bootstrap-servers: localhost:9092

logging:
  level:
    #http request logging
    org.apache.coyote.http11: debug
#    com.example.notiservice: debug
