spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/noti?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  data:
    mongodb:
      host: localhost
      port: 27017
      database: noti
#      authentication-database: admin
      username: noti
      password: noti

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: noti
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
  level:
    #http request logging
    org.apache.coyote.http11: debug
#    com.example.notiservice: debug
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
